### ISSUE TITLE
模板页面无法解析

### ISSUE THREAD

**Issue by niniun1024** [fouber/fis-java-jsp#3]
服务器启动后访问 http://127.0.0.1:8080/ ，页面上只显示index几个字，直接访问 http://127.0.0.1:8080/ index.jsp，smarty无法解析，请问是哪里的问题？访问index.jsp页面报错如下：
Fatal error: Uncaught exception 'SmartyException' with message 'Unable to load template file 'C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\template/index.jsp/index.tpl'' in C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\smarty\sysplugins\smarty_internal_templatebase.php:127 Stack trace: #0 C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\smarty\sysplugins\smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('C:\Users\Xiao10...', NULL, NULL, NULL, true) #1 C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\fisdata\TestData.class.php(100): Smarty_Internal_TemplateBase->display('C:\Users\Xiao10...') #2 C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\index.php(53): TestData::renderHelper(Object(Smarty), 'C:\Users\Xiao10...') #3 C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\index.php(146): fis_debug_render_smarty() #4 {main} thrown in C:\Users\Xiao106347\AppData\Local.fis-plus-tmp\www\smarty\sysplugins\smarty_internal_templatebase.php on line 127

**Comment by fouber** [comment]
@jyy12 

跟smarty什么关系。。。这个git展示的是fis和java项目结合的效果。你应该还是用的fis-plus或者fisp吧，fis-plus是fis面向smarty项目的一套系统，它不是原生的fis，而是一个包装版的，面向百度的方案，不能运行这个git所介绍的项目。

**Comment by fouber** [comment]
@jyy12 

运行这个项目使用的是原生的fis，安装的方式是：

npm install -g fis

fis-plus不能用来尝试任何其他项目，只能用来构建smarty的。

**Comment by niniun1024** [comment]
可以了，是把fis与fisp搞混了，谢谢

**Comment by xiaojingrui** [comment]
好像现在不能运行了，是和fis和java的版本有关吗，现在是直接显示下面这样

index.jsp
map
node_modules
package.json
server.js
server.log
static
WEB-INF
widget
